version: '2'
services:
  poc-postgres:
    image: postgres:10.1-alpine
    restart: always
    environment:
      POSTGRES_USER: poc
      POSTGRES_PASSWORD: poc
      POSTGRES_DB: poc
    links:
       - "poc-eureka"
  poc-eureka:
    image: springcloud/eureka
    restart: always
    ports:
      - 8761:8761



version: '2'
services:
  poc-postgres:
    image: postgres:10.1-alpine
    restart: always
    environment:
      POSTGRES_USER: poc
      POSTGRES_PASSWORD: poc
      POSTGRES_DB: poc
    ports:
      - 5432:5432
  poc-eureka:
    image: springcloud/eureka
    restart: always
    ports:
      - 8761:8761



FROM openjdk:8-jre-alpine
COPY poc-data/target/poc-data-0.0.1-SNAPSHOT.jar /usr/src/poc/poc-data.jar
COPY poc-client/target/poc-client-0.0.1-SNAPSHOT.jar /usr/src/poc/poc-client.jar
COPY poc-zuul/target/poc-zuul-0.0.1-SNAPSHOT.jar /usr/src/poc/poc-zuul.jar
WORKDIR /usr/src/poc
CMD ["java", "-jar","poc-data.jar","&"]
CMD ["java", "-jar","poc-client.jar","&"]
CMD ["java", "-jar","poc-zuul.jar","&"]
