version: '2'
services:
  poc-postgres:
    image: postgres:10.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: poc
      POSTGRES_PASSWORD: poc
      POSTGRES_DB: poc
  poc-data:
    image: frkr/poc-data
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - poc-postgres
      - poc-eureka
  poc-client:
    image: frkr/poc-client
    restart: always
    ports:
      - 9191:9191
    depends_on:
      - poc-data
  poc-zuul:
    image: frkr/poc-zuul
    restart: always
    depends_on:
      - poc-client
    ports:
      - 8888:8080
