eureka:
  client:
    serviceUrl:
      defaultZone: http://poc-eureka:8761/eureka/

spring:
  application:
    name: poc-zuul

server:
  port: 8080

zuul:
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    data:
      path: /data/**
      url: http://poc-data:9090
    poc:
      path: /poc/**
      url: http://poc-client:9191
    static:
      path: /static/**
